[package]
name = "stalkr"
version = "0.1.0"
authors = [ "varsity <varsity@duck.com>" ]
description = "Looks up the given alias on several social networks, then returns the valid results."
edition = "2021"

[dependencies]
reqwest = { version = "*", features = [ "blocking" ] }
arguments = "*"
